### ISSUE TITLE
'server' and 'help' cannot be used in the command sent to the server

### ISSUE THREAD

**Issue by dasisdormax** [klemens/rconc#1]
I found the following unexpected behaviour when testing with a CS:GO server:

When executing `./target/release/rconc localhost:27015 help`, rconc displays the help to itself instead of executing the help command on the server. The same applies to the word 'server' or if these words are in a different position (like in `say Type /help for help`)

**Comment by klemens** [comment]
Yes, this is a limitation of the `clap` argument parser.
As a workaround you can use `rconc *server* -- help` instead of `rconc *server* help`.

**Comment by dasisdormax** [comment]
Thanks for the info. I'll be fine with that workaround (though I haven't been able to try yet)

**Comment by klemens** [comment]
Turns out I totally forgot that I already reported this issue [upstream](https://github.com/kbknapp/clap-rs/issues/793) and it was fixed by the developer quite fast. As this fix is now included in the latest `clap` release, I have updated `rconc` with it.

So `rconc *server* help` or `rconc *server* say Type /help ..` should work fine now.
